# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request 
# events but only for the master branch
on:
  push:
    branches: [ test-flow ]
  pull_request:
    branches: [ master ]

jobs:
  clone-source:
    runs-on: ubuntu-latest
    steps:
    - name: Clone source
      uses: actions/checkout@v2
      with:
          repository: 'https://github.com/CSSEGISandData/COVID-19'
      run: |
        cp -r csse_covid_19_data/csse_covid_19_time_series/ .
        ls -al .

        
