name: Update data from CSSEGISandData

on: 
  schedule:
    - cron:  '0 * * * *'

jobs:
  clone-source:
    runs-on: ubuntu-latest
    steps:
    - name: Clone source
      uses: actions/checkout@v2
      with:
          repository: 'CSSEGISandData/COVID-19'
    - name: Copy files
      run: |
        mkdir csv
        mv csse_covid_19_data/csse_covid_19_time_series/time_series_19-covid-Confirmed.csv csv/confirmed.csv
        mv csse_covid_19_data/csse_covid_19_time_series/time_series_19-covid-Deaths.csv csv/deaths.csv
        mv csse_covid_19_data/csse_covid_19_time_series/time_series_19-covid-Recovered.csv csv/recovered.csv
    - name: Upload files
      uses: actions/upload-artifact@v1
      with:
        name: csv
        path: csv
  update-data:
    needs: clone-source
    runs-on: ubuntu-latest
    steps:
    - name: Clone our repo
      uses: actions/checkout@v2
      with:
          repository: 'enrichman/covid19'
          ref: 'master'
    - name: Download files
      uses: actions/download-artifact@v1
      with:
        name: csv
        path: csv
    - name: Generate new files
      run: |
        go build .
        ./covid19
        rm covid19
    - name: Push on our repo
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add -A
        git diff-index --quiet HEAD || git commit -m 'Update data'
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: master
    - name: Upload files
      uses: actions/upload-artifact@v1
      with:
        name: world
        path: world
  create-site:
    needs: update-data
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.ENRICHMAN_GH_TOKEN }}
        repository: 'enrichman/enrichman.github.io'
    - name: Download files
      uses: actions/download-artifact@v1
      with:
        name: world
        path: covid19/world
    - name: Run a multi-line script
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add covid19
        git diff-index --quiet HEAD || git commit -m 'Update world data'
    
    - uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.ENRICHMAN_GH_TOKEN }}
        repository: 'enrichman/enrichman.github.io'
